### dim, shape, size

In [2]:
import torch

t = torch.FloatTensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(t.dim())
print(t.shape)
print(t.size())

2
torch.Size([3, 3])
torch.Size([3, 3])


### matmul

In [3]:
m1 = torch.FloatTensor([[0., 1., 2.,],[ 3., 4., 5.],[ 6.,7.,8.,]])
m2 = torch.FloatTensor([[0,1],[2,3],[3,4]])
m1.matmul(m2)

tensor([[ 8., 11.],
        [23., 35.],
        [38., 59.]])

### mean

In [4]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t.mean())
print(t.mean(dim=0)) # 0번축 기준으로 mean계산
print(t.mean(dim=1)) # 1번축 기준으로 mean계산
print(t.mean(dim=-1)) # 마지막 축 기준으로 mean계산

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### squeeze

In [5]:
f = torch.FloatTensor([[1],[2],[3]])
print(f.shape)

f = f.squeeze()
print(f)
print(f.shape)

torch.Size([3, 1])
tensor([1., 2., 3.])
torch.Size([3])


### unsqueeze

In [7]:
f = torch.FloatTensor([1,2,3])
print(f.shape)

f1 = f.unsqueeze(0)
print(f1.shape)
print(f1)

f2 = f.unsqueeze(1)
print(f2.shape)
print(f2)

torch.Size([3])
torch.Size([1, 3])
tensor([[1., 2., 3.]])
torch.Size([3, 1])
tensor([[1.],
        [2.],
        [3.]])


### type casting

In [8]:
a = torch.LongTensor([1,2,3,4,5])
b = torch.ByteTensor([True, False])
print(a.float().type())
print(b.float().type())
print(a.byte().type())
print(b.long().type())

torch.FloatTensor
torch.FloatTensor
torch.ByteTensor
torch.LongTensor


### stack

In [9]:
x = torch.FloatTensor([1,2])
y = torch.FloatTensor([3,4])
z = torch.FloatTensor([5,6])

print(torch.stack([x,y,z]))
print(torch.stack([x,y,z], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 3., 5.],
        [2., 4., 6.]])


### like function

In [10]:
x = torch.ones_like(x)
y = torch.zeros_like(y)
print(x)
print(y)

tensor([1., 1.])
tensor([0., 0.])


### in-place operation

In [11]:
x = torch.FloatTensor([[1,2],[3,4,]])
x.mul(2) # 원본 x는 변화 없이 결과 반환만 됨
print(x)
x.mul_(2) # 원본 x자체가 변함
print(x)

tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
