### input data 처리

In [1]:
import numpy as np
import torch
import torch.optim as optim

sample = "hihello"

char_set = list(set(sample)) # 중복 제거를 위해 set을 사용해서 위의 표와는 다른 index들이 나옴
input_size = len(char_set)
hidden_size = len(char_set)
learning_rate = 0.1

input_sequence = sample[:-1]
output_sequence = sample[1:]

# input, output sequence to char_set index
x_data = [list(map(char_set.index, input_sequence))]
y_data = [list(map(char_set.index, output_sequence))]

# x_data one hotencoding
targets = np.array(x_data)
x_one_hot = np.eye(input_size)[targets] # list indexing

print(f"x_data : {x_data}")
print(f"y_data : {y_data}")
print(f"x_one_hot : {x_one_hot}")

x_data : [[4, 1, 4, 3, 2, 2]]
y_data : [[1, 4, 3, 2, 2, 0]]
x_one_hot : [[[0. 0. 0. 0. 1.]
  [0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 1. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 1. 0. 0.]]]


### To tensor

In [2]:
X = torch.FloatTensor(x_one_hot)
Y = torch.LongTensor(y_data)

### model, loss, optimizer

In [3]:
# RNN
# batch_frist옵션으로 가장 앞 dim이 batch_size가 되도록
rnn = torch.nn.RNN(input_size, hidden_size, batch_first=True)

# loss & optimizer
criterion = torch.nn.CrossEntropyLoss()
optimizer = optim.Adam(rnn.parameters(), learning_rate)

In [4]:
epochs = 100
for epoch in range(epochs):
    optimizer.zero_grad()
    output, _status = rnn(X)
    loss = criterion(output.view(-1, input_size), Y.view(-1))
    loss.backward()
    optimizer.step()
    result = output.data.numpy().argmax(axis = 2)
    result_str = ''.join([char_set[c] for c in np.squeeze(result)])
    print(f" {epoch}/{epochs} : loss : {loss.item()}, result = {result_str}")

 0/100 : loss : 1.5556267499923706, result = ooholl
 1/100 : loss : 1.43287193775177, result = oololl
 2/100 : loss : 1.323917269706726, result = lollll
 3/100 : loss : 1.215421199798584, result = illlll
 4/100 : loss : 1.1222037076950073, result = ihelll
 5/100 : loss : 1.0601412057876587, result = ihelll
 6/100 : loss : 1.0056649446487427, result = ihelll
 7/100 : loss : 0.9549684524536133, result = ihelll
 8/100 : loss : 0.9277551174163818, result = ihelll
 9/100 : loss : 0.8953915238380432, result = ihelll
 10/100 : loss : 0.8703381419181824, result = ihelll
 11/100 : loss : 0.8513872623443604, result = ihelll
 12/100 : loss : 0.8328230977058411, result = ihelll
 13/100 : loss : 0.8206679821014404, result = ihelll
 14/100 : loss : 0.7994511723518372, result = ihelll
 15/100 : loss : 0.7981094717979431, result = ihelll
 16/100 : loss : 0.7796568870544434, result = ihelll
 17/100 : loss : 0.7748346924781799, result = ihelll
 18/100 : loss : 0.7538755536079407, result = ihelll
 19/100